using System.ComponentModel.DataAnnotations;using Kaizen.Infrastructure.Persistence;using Kaizen.Domain.Entities;using Kaizen.Web.Services;using Kaizen.Domain.Rules;using Kaizen.Web.ViewModels;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Diagnostics;
namespace Kaizen.Tests;
public class ActionVersioningTests
{
 private static ApplicationDbContext Context()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).ConfigureWarnings(x=>x.Ignore(InMemoryEventId.TransactionIgnoredWarning)).Options);
 private static async Task<(ApplicationDbContext Db,ReviewService Service,KaizenReviewFormViewModel Vm,AccionPlanificada Action)> Setup(){var db=Context();var start=new DateOnly(2026,8,1);var goal=new Meta{Titulo="Meta",Descripcion="D",PorQueEsImportante="I",SituacionActual="C",ResultadoEsperado="E",MetricaProgreso="M",AreaPersonal=new(){Nombre="Área"},FechaInicio=start,Estado=EstadoMeta.Activa};var action=new AccionPlanificada{Meta=goal,Nombre="Caminar",Frecuencia=FrecuenciaAccion.Diaria,FechaInicio=start,VigenteDesde=start,CantidadObjetivo=30,UnidadMetrica="min",Estado=EstadoAccion.Activa};db.AddRange(new AccionProgramada{AccionPlanificada=action,FechaProgramada=start,Estado=EstadoCumplimiento.Completada,Registro=new(){Estado=EstadoCumplimiento.Completada}},new AccionProgramada{AccionPlanificada=action,FechaProgramada=new(2026,8,6),Estado=EstadoCumplimiento.NoRealizada,Registro=new(){Estado=EstadoCumplimiento.NoRealizada}},new AccionProgramada{AccionPlanificada=action,FechaProgramada=new(2026,8,7),Estado=EstadoCumplimiento.Pendiente});await db.SaveChangesAsync();var service=new ReviewService(db,new(db));var vm=(await service.BuildAsync(goal.Id,new(2026,8,3)))!;vm.QueFunciono="W";vm.QueDificulto="H";vm.Aprendizaje="L";vm.CambioProximoPeriodo="N";return(db,service,vm,action);}
 [Theory][InlineData(TipoAjuste.Aumentar,45)][InlineData(TipoAjuste.Simplificar,15)]public async Task Adjustment_creates_non_overlapping_version(TipoAjuste type,int amount){var(db,service,vm,old)=await Setup();vm.Decisions[0].Tipo=type;vm.Decisions[0].Motivo="Cambio gradual";vm.Decisions[0].NewTargetAmount=amount;await service.SaveAsync(vm,default);var versions=await db.AccionesPlanificadas.OrderBy(x=>x.Version).ToListAsync();Assert.Equal(2,versions.Count);Assert.Equal(versions[0].VigenteHasta!.Value.AddDays(1),versions[1].VigenteDesde);Assert.Equal(old.SerieAccionId,versions[1].SerieAccionId);Assert.Equal(amount,versions[1].CantidadObjetivo);}
 [Fact]public async Task Replace_links_new_version_and_preserves_registered_future_occurrence(){var(db,service,vm,old)=await Setup();vm.Decisions[0].Tipo=TipoAjuste.Reemplazar;vm.Decisions[0].Motivo="Nueva estrategia";vm.Decisions[0].NewName="Bicicleta";await service.SaveAsync(vm,default);var next=await db.AccionesPlanificadas.SingleAsync(x=>x.Version==2);Assert.Equal(old.Id,next.VersionAnteriorId);Assert.Equal("Bicicleta",next.Nombre);Assert.True(await db.AccionesProgramadas.AnyAsync(x=>x.AccionPlanificadaId==old.Id&&x.Estado==EstadoCumplimiento.NoRealizada));Assert.False(await db.AccionesProgramadas.AnyAsync(x=>x.AccionPlanificadaId==old.Id&&x.Estado==EstadoCumplimiento.Pendiente));}
 [Fact]public async Task Complete_closes_action_without_changing_past_log(){var(db,service,vm,old)=await Setup();vm.Decisions[0].Tipo=TipoAjuste.Completar;await service.SaveAsync(vm,default);Assert.Equal(EstadoAccion.Completada,(await db.AccionesPlanificadas.SingleAsync()).Estado);Assert.True(await db.AccionesProgramadas.AnyAsync(x=>x.AccionPlanificadaId==old.Id&&x.Estado==EstadoCumplimiento.Completada));Assert.Single(db.RegistrosAccion.Where(x=>x.Estado==EstadoCumplimiento.Completada));}
 [Fact]public void Retroactive_adjustment_is_rejected(){var vm=new KaizenReviewFormViewModel{InicioPeriodo=new(2026,8,1),FinPeriodo=new(2026,8,3),QueFunciono="W",QueDificulto="H",Aprendizaje="L",CambioProximoPeriodo="N",Decisions=[new(){AccionPlanificadaId=1,Tipo=TipoAjuste.Aumentar,FechaVigencia=new(2026,8,3),Motivo="R"}]};var errors=new List<ValidationResult>();Validator.TryValidateObject(vm,new(vm),errors,true);Assert.Contains(errors,x=>x.ErrorMessage!.Contains("posterior"));}
}
