using Kaizen.Application.DailyActions;using Kaizen.Infrastructure.Persistence;using Kaizen.Domain.Entities;using Microsoft.EntityFrameworkCore;
namespace Kaizen.Tests;
public class DailyActionUseCaseTests
{
 private static ApplicationDbContext Context(){var options=new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).Options;return new(options);}
 private static async Task<(ApplicationDbContext Db,RegisterDailyAction Register,UndoDailyAction Undo,AccionProgramada Entry)> Setup(DateOnly date){var db=Context();var goal=new Meta{Titulo="Meta",Descripcion="D",PorQueEsImportante="I",SituacionActual="C",ResultadoEsperado="E",MetricaProgreso="M",Estado=EstadoMeta.Activa,AreaPersonal=new(){Nombre="Área"}};var action=new AccionPlanificada{Meta=goal,Nombre="Acción",FechaInicio=date,Frecuencia=FrecuenciaAccion.Diaria};var entry=new AccionProgramada{AccionPlanificada=action,FechaProgramada=date};db.Add(entry);await db.SaveChangesAsync();var repository=new DailyActionRepository(db);return(db,new(repository),new(repository),entry);}
 [Fact]public async Task Registers_completed_action_once(){var today=new DateOnly(2026,8,4);var(db,register,_,entry)=await Setup(today);await register.ExecuteAsync(entry.Id,EstadoCumplimiento.Completada,10,"Bien",today);await register.ExecuteAsync(entry.Id,EstadoCumplimiento.Completada,12,"Mejor",today);Assert.Equal(1,await db.RegistrosAccion.CountAsync());Assert.Equal(12,(await db.RegistrosAccion.SingleAsync()).ValorReal);}
 [Fact]public async Task Registers_missed_action(){var today=new DateOnly(2026,8,4);var(db,register,_,entry)=await Setup(today);var result=await register.ExecuteAsync(entry.Id,EstadoCumplimiento.NoRealizada,null,"No pude",today);Assert.True(result.Success);Assert.Equal(EstadoCumplimiento.NoRealizada,(await db.AccionesProgramadas.SingleAsync()).Estado);}
 [Fact]public async Task Rejects_action_from_another_day(){var today=new DateOnly(2026,8,4);var(_,register,_,entry)=await Setup(today.AddDays(-1));var result=await register.ExecuteAsync(entry.Id,EstadoCumplimiento.Completada,null,null,today);Assert.False(result.Success);}
 [Fact]public async Task Undo_removes_log_and_restores_pending(){var today=new DateOnly(2026,8,4);var(db,register,undo,entry)=await Setup(today);await register.ExecuteAsync(entry.Id,EstadoCumplimiento.Completada,null,null,today);await undo.ExecuteAsync(entry.Id,today);Assert.Empty(db.RegistrosAccion);Assert.Equal(EstadoCumplimiento.Pendiente,(await db.AccionesProgramadas.SingleAsync()).Estado);}
 [Fact]public async Task Reorders_all_actions_for_the_day(){var date=new DateOnly(2026,8,4);var(db,_,_,first)=await Setup(date);var second=new AccionProgramada{AccionPlanificada=new AccionPlanificada{Meta=first.AccionPlanificada!.Meta,Nombre="Segunda",FechaInicio=date,Frecuencia=FrecuenciaAccion.Diaria},FechaProgramada=date};db.Add(second);await db.SaveChangesAsync();var service=new ReorderDailyActions(new DailyActionRepository(db));var result=await service.ExecuteAsync([second.Id,first.Id],date);Assert.True(result.Success);Assert.Equal(1,second.Orden);Assert.Equal(2,first.Orden);}
 [Fact]public async Task Rejects_an_incomplete_daily_order(){var date=new DateOnly(2026,8,4);var(db,_,_,first)=await Setup(date);db.Add(new AccionProgramada{AccionPlanificada=new AccionPlanificada{Meta=first.AccionPlanificada!.Meta,Nombre="Segunda",FechaInicio=date,Frecuencia=FrecuenciaAccion.Diaria},FechaProgramada=date});await db.SaveChangesAsync();var result=await new ReorderDailyActions(new DailyActionRepository(db)).ExecuteAsync([first.Id],date);Assert.False(result.Success);Assert.All(await db.AccionesProgramadas.ToListAsync(),x=>Assert.Equal(0,x.Orden));}
}
