using Kaizen.Infrastructure.Persistence;using Kaizen.Domain.Entities;using Kaizen.Web.Services;using Kaizen.Domain.Rules;using Kaizen.Web.ViewModels;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Diagnostics;
namespace Kaizen.Tests;
public class GoalActivationServiceTests
{
 private static ApplicationDbContext Context(){var options=new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).ConfigureWarnings(x=>x.Ignore(InMemoryEventId.TransactionIgnoredWarning)).Options;return new(options);}
 private static GoalSetupViewModel Model(int areaId,string intent)=>new(){SubmitIntent=intent,Titulo="Meta",Descripcion="Descripción",AreaPersonalId=areaId,FechaInicio=new(2026,8,4),MetricaProgreso="Sesiones",PorQueEsImportante="Importa",SituacionActual="Actual",ResultadoEsperado="Deseado",Obstaculos="Tiempo",MejoraMasPequena="Cinco minutos",EvidenciaMejora="Registro",Acciones=[new(){Nombre="Practicar",Frecuencia=FrecuenciaAccion.Diaria,FechaInicio=new(2026,8,4)}]};
 [Fact]public async Task Draft_does_not_generate_scheduled_events(){var db=Context();var area=new AreaPersonal{Nombre="Área"};db.Add(area);await db.SaveChangesAsync();var vm=Model(area.Id,"draft");var service=new GoalActivationService(db,new(db),new UsuarioActualPrueba("usuario-1"));await service.SaveAsync(vm,false,default);Assert.Equal(EstadoMeta.Borrador,(await db.Metas.SingleAsync()).Estado);Assert.Empty(db.AccionesProgramadas);}
 [Fact]public async Task Valid_draft_can_be_activated_with_bounded_occurrences(){var db=Context();var area=new AreaPersonal{Nombre="Área"};db.Add(area);await db.SaveChangesAsync();var service=new GoalActivationService(db,new(db),new UsuarioActualPrueba("usuario-1"));var draft=Model(area.Id,"draft");var id=await service.SaveAsync(draft,false,default);var activate=Model(area.Id,"activate");activate.Id=id;await service.SaveAsync(activate,true,default);Assert.Equal(EstadoMeta.Activa,(await db.Metas.SingleAsync()).Estado);Assert.InRange(await db.AccionesProgramadas.CountAsync(),1,ScheduleService.MaximumHorizonDays+1);}
}
