using Kaizen.Infrastructure.Persistence;using Kaizen.Domain.Entities;using Kaizen.Web.Services;using Kaizen.Domain.Rules;using Kaizen.Web.ViewModels;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Diagnostics;using Microsoft.Extensions.Logging.Abstractions;
namespace Kaizen.Tests;
public class ManualActionEditServiceTests
{
 private static ApplicationDbContext Context()=>new(new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).ConfigureWarnings(x=>x.Ignore(InMemoryEventId.TransactionIgnoredWarning)).Options);
 private static ManualActionEditService Service(ApplicationDbContext db)=>new(db,new(db),NullLogger<ManualActionEditService>.Instance);
 private static async Task<(ApplicationDbContext Db,Meta Meta,AccionPlanificada Action)> Seed(EstadoMeta status)
 {
  var db=Context();var today=DateOnly.FromDateTime(DateTime.Today);var goal=new Meta{Titulo="Meta",Descripcion="D",PorQueEsImportante="I",SituacionActual="C",ResultadoEsperado="E",MetricaProgreso="M",AreaPersonal=new(){Nombre="Área"},FechaInicio=today.AddDays(-10),Estado=status,FechaActivacion=status==EstadoMeta.Activa?DateTime.UtcNow:null};var action=new AccionPlanificada{Meta=goal,Nombre="Caminar",Descripcion="Inicial",Frecuencia=FrecuenciaAccion.Diaria,FechaInicio=today.AddDays(-10),VigenteDesde=today.AddDays(-10),CantidadObjetivo=30,UnidadMetrica="min",Estado=EstadoAccion.Activa};db.Add(action);await db.SaveChangesAsync();return(db,goal,action);
 }
 private static async Task<ActionEditViewModel> Edit(ManualActionEditService service,int id,DateOnly effective){var vm=(await service.BuildAsync(id))!;vm.CantidadObjetivo=45;vm.FechaVigencia=effective;vm.Motivo="Aumento gradual";await service.PrepareAsync(vm);return vm;}

 [Fact]public async Task Draft_without_history_is_updated_without_new_version(){var(db,_,a)=await Seed(EstadoMeta.Borrador);var service=Service(db);var vm=await Edit(service,a.Id,DateOnly.FromDateTime(DateTime.Today));var result=await service.SaveAsync(vm,default);Assert.Equal(ManualEditOutcome.Updated,result.Outcome);Assert.Single(db.AccionesPlanificadas);Assert.Equal(45,(await db.AccionesPlanificadas.SingleAsync()).CantidadObjetivo);}

 [Fact]public async Task Active_action_creates_linked_non_overlapping_version(){var(db,_,a)=await Seed(EstadoMeta.Activa);var effective=DateOnly.FromDateTime(DateTime.Today).AddDays(2);var result=await Service(db).SaveAsync(await Edit(Service(db),a.Id,effective),default);var versions=await db.AccionesPlanificadas.OrderBy(x=>x.Version).ToListAsync();Assert.Equal(ManualEditOutcome.VersionCreated,result.Outcome);Assert.Equal(2,versions.Count);Assert.Equal(effective.AddDays(-1),versions[0].VigenteHasta);Assert.Equal(effective,versions[1].VigenteDesde);Assert.Equal(versions[0].Id,versions[1].VersionAnteriorId);Assert.Equal(versions[0].SerieAccionId,versions[1].SerieAccionId);}

 [Fact]public async Task Future_logged_occurrence_is_preserved_but_unlogged_pending_is_replaced(){var(db,_,a)=await Seed(EstadoMeta.Activa);var today=DateOnly.FromDateTime(DateTime.Today);var pending=new AccionProgramada{AccionPlanificada=a,FechaProgramada=today.AddDays(3),Estado=EstadoCumplimiento.Pendiente};var registered=new AccionProgramada{AccionPlanificada=a,FechaProgramada=today.AddDays(4),Estado=EstadoCumplimiento.Completada,Registro=new(){Estado=EstadoCumplimiento.Completada}};db.AddRange(pending,registered);await db.SaveChangesAsync();var service=Service(db);var vm=await Edit(service,a.Id,today.AddDays(2));await service.SaveAsync(vm,default);Assert.False(await db.AccionesProgramadas.AnyAsync(x=>x.Id==pending.Id));Assert.True(await db.AccionesProgramadas.AnyAsync(x=>x.Id==registered.Id&&x.AccionPlanificadaId==a.Id));Assert.Single(db.RegistrosAccion);}

 [Fact]public async Task Closed_review_rejects_retroactive_effective_date(){var(db,g,a)=await Seed(EstadoMeta.Activa);var today=DateOnly.FromDateTime(DateTime.Today);db.Add(new RevisionKaizen{MetaId=g.Id,InicioPeriodo=today.AddDays(-7),FinPeriodo=today.AddDays(2),QueFunciono="W",QueDificulto="H",AjustePequeno="S",Aprendizaje="L",CambioProximoPeriodo="N",FechaProximaRevision=today.AddDays(9)});await db.SaveChangesAsync();var service=Service(db);var vm=await Edit(service,a.Id,today.AddDays(1));Assert.Equal(ManualActionEditService.InvalidDate,await service.ValidateEffectiveDateAsync(vm));}

 [Fact]public async Task No_real_change_does_not_create_version(){var(db,_,a)=await Seed(EstadoMeta.Activa);var service=Service(db);var vm=(await service.BuildAsync(a.Id))!;vm.Motivo="Sin cambios";await service.PrepareAsync(vm);Assert.Empty(vm.Changes);var result=await service.SaveAsync(vm,default);Assert.Equal(ManualEditOutcome.NoChanges,result.Outcome);Assert.Single(db.AccionesPlanificadas);Assert.Empty(db.EventosHistorialMeta);}

 [Fact]public async Task Manual_history_contains_only_changed_values_and_origin_is_not_review(){var(db,_,a)=await Seed(EstadoMeta.Activa);var service=Service(db);await service.SaveAsync(await Edit(service,a.Id,DateOnly.FromDateTime(DateTime.Today).AddDays(1)),default);var history=await db.EventosHistorialMeta.SingleAsync();var next=await db.AccionesPlanificadas.SingleAsync(x=>x.Version==2);Assert.Equal(TipoEventoHistorialMeta.AccionModificadaManualmente,history.Tipo);Assert.Contains("Cantidad",history.ValoresAnteriores);Assert.DoesNotContain("Frecuencia",history.ValoresAnteriores);Assert.Null(next.RevisionOrigenId);}

 [Fact]public async Task Stale_double_submission_is_rejected(){var(db,_,a)=await Seed(EstadoMeta.Activa);var service=Service(db);var vm=await Edit(service,a.Id,DateOnly.FromDateTime(DateTime.Today).AddDays(1));await service.SaveAsync(vm,default);var error=await Assert.ThrowsAsync<InvalidOperationException>(()=>service.SaveAsync(vm,default));Assert.Contains("ya cambió",error.Message);Assert.Equal(2,await db.AccionesPlanificadas.CountAsync());}
}
