using Kaizen.Infrastructure.Persistence;using Kaizen.Domain.Entities;using Kaizen.Web.Services;using Kaizen.Domain.Rules;using Kaizen.Web.ViewModels;using Microsoft.EntityFrameworkCore;using Microsoft.EntityFrameworkCore.Diagnostics;
namespace Kaizen.Tests;
public class ReviewServiceTests
{
 private static ApplicationDbContext Context(){var options=new DbContextOptionsBuilder<ApplicationDbContext>().UseInMemoryDatabase(Guid.NewGuid().ToString()).ConfigureWarnings(x=>x.Ignore(InMemoryEventId.TransactionIgnoredWarning)).Options;return new(options);}
 private static async Task<(ApplicationDbContext Db,ReviewService Service,Meta Meta,AccionPlanificada Action)> Setup(){var db=Context();var start=new DateOnly(2026,8,1);var goal=new Meta{Titulo="Meta",Descripcion="D",PorQueEsImportante="I",SituacionActual="C",ResultadoEsperado="E",MetricaProgreso="M",AreaPersonal=new(){Nombre="Área"},FechaInicio=start,Estado=EstadoMeta.Activa,FechaProximaRevision=new(2026,8,8)};var action=new AccionPlanificada{Meta=goal,Nombre="Caminar",Frecuencia=FrecuenciaAccion.Diaria,FechaInicio=start,VigenteDesde=start,CantidadObjetivo=30,UnidadMetrica="min",Estado=EstadoAccion.Activa};db.AddRange(new AccionProgramada{AccionPlanificada=action,FechaProgramada=start,Estado=EstadoCumplimiento.Completada,Registro=new(){Estado=EstadoCumplimiento.Completada,ValorReal=30,Nota="Bien"}},new AccionProgramada{AccionPlanificada=action,FechaProgramada=start.AddDays(1),Estado=EstadoCumplimiento.NoRealizada},new AccionProgramada{AccionPlanificada=action,FechaProgramada=start.AddDays(2),Estado=EstadoCumplimiento.Pendiente});await db.SaveChangesAsync();return(db,new(db,new(db)),goal,action);}
 private static void Reflect(KaizenReviewFormViewModel vm){vm.QueFunciono="La rutina";vm.QueDificulto="El clima";vm.Aprendizaje="Preparar antes";vm.CambioProximoPeriodo="Ajustar gradualmente";}
 [Fact]public async Task First_review_uses_goal_start_and_real_counts(){var(_,service,_,_)=await Setup();var vm=await service.BuildAsync(1,new(2026,8,3));Assert.NotNull(vm);Assert.Equal(new DateOnly(2026,8,1),vm!.InicioPeriodo);Assert.Equal((1,1,1),(vm.Completed,vm.Missed,vm.Pending));Assert.Equal(33.33m,vm.PorcentajeCumplimiento);Assert.Contains("Bien",vm.Notes);}
 [Fact]public async Task Zero_actions_does_not_divide_by_zero(){var db=Context();db.Add(new Meta{Titulo="Vacía",Descripcion="D",PorQueEsImportante="I",SituacionActual="C",ResultadoEsperado="E",MetricaProgreso="M",AreaPersonal=new(){Nombre="Área"},FechaInicio=new(2026,8,1),Estado=EstadoMeta.Activa});await db.SaveChangesAsync();var vm=await new ReviewService(db,new(db)).BuildAsync(1,new(2026,8,3));Assert.Equal(0,vm!.PorcentajeCumplimiento);}
 [Fact]public async Task Maintain_records_decision_without_new_version(){var(db,service,_,_)=await Setup();var vm=(await service.BuildAsync(1,new(2026,8,3)))!;Reflect(vm);await service.SaveAsync(vm,default);Assert.Single(db.AccionesPlanificadas);Assert.Equal(TipoAjuste.Mantener,(await db.AjustesPlan.SingleAsync()).Tipo);}
 [Fact]public async Task Simplify_closes_old_and_creates_linked_version(){var(db,service,_,old)=await Setup();var vm=(await service.BuildAsync(1,new(2026,8,3)))!;Reflect(vm);vm.Decisions[0].Tipo=TipoAjuste.Simplificar;vm.Decisions[0].Motivo="Era exigente";vm.Decisions[0].NewTargetAmount=20;await service.SaveAsync(vm,default);var versions=await db.AccionesPlanificadas.OrderBy(x=>x.Version).ToListAsync();Assert.Equal(2,versions.Count);Assert.Equal(new DateOnly(2026,8,3),versions[0].VigenteHasta);Assert.Equal(old.Id,versions[1].VersionAnteriorId);Assert.Equal(20,versions[1].CantidadObjetivo);Assert.Equal(3,await db.AccionesProgramadas.CountAsync(x=>x.FechaProgramada<=new DateOnly(2026,8,3)));}
 [Fact]public async Task Pause_and_complete_do_not_rewrite_historical_logs(){var(db,service,_,_)=await Setup();var vm=(await service.BuildAsync(1,new(2026,8,3)))!;Reflect(vm);vm.Decisions[0].Tipo=TipoAjuste.Pausar;await service.SaveAsync(vm,default);Assert.Equal(EstadoAccion.Pausada,(await db.AccionesPlanificadas.SingleAsync()).Estado);Assert.Single(db.RegistrosAccion);}
 [Fact]public async Task Duplicate_period_is_rejected(){var(_,service,_,_)=await Setup();var vm=(await service.BuildAsync(1,new(2026,8,3)))!;Reflect(vm);await service.SaveAsync(vm,default);await Assert.ThrowsAsync<InvalidOperationException>(()=>service.SaveAsync(vm,default));}
 [Fact]public async Task Next_period_starts_day_after_previous_end(){var(db,service,goal,_)=await Setup();db.Add(new RevisionKaizen{Meta=goal,InicioPeriodo=new(2026,8,1),FinPeriodo=new(2026,8,3),QueFunciono="W",QueDificulto="H",AjustePequeno="A",Aprendizaje="L",CambioProximoPeriodo="N",FechaProximaRevision=new(2026,8,10)});await db.SaveChangesAsync();var vm=await service.BuildAsync(goal.Id,new(2026,8,5));Assert.Equal(new DateOnly(2026,8,4),vm!.InicioPeriodo);}
 [Fact]public async Task History_is_filtered_ordered_limited_and_read_only(){var(db,_,g,a)=await Setup();g.FechaCreacion=new DateTime(2026,7,1,0,0,0,DateTimeKind.Utc);var log=await db.RegistrosAccion.SingleAsync();log.FechaRegistro=new DateTime(2026,8,1,12,0,0,DateTimeKind.Utc);db.AddRange(new EventoHistorialMeta{Meta=g,AccionPlanificada=a,Tipo=TipoEventoHistorialMeta.Activada,Descripcion="Primero",FechaOcurrencia=new(2026,8,1)},new EventoHistorialMeta{Meta=g,Tipo=TipoEventoHistorialMeta.Revision,Descripcion="Último",FechaOcurrencia=new(2026,8,3)});await db.SaveChangesAsync();var before=db.ChangeTracker.Entries().Count();var items=await new GoalHistoryService(db).GetAsync(g.Id,1,1);Assert.Single(items);Assert.Equal("Último",items[0].Descripcion);Assert.Equal(before,db.ChangeTracker.Entries().Count());}
}
