using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Kaizen.Infrastructure.Migrations;

public partial class NombresDominioEnEspanol : Migration
{
    protected override void Up(MigrationBuilder migrationBuilder)
    {
            migrationBuilder.RenameColumn(name: "ActionPlanItemId", table: "ScheduledActions", newName: "AccionPlanificadaId");
            migrationBuilder.RenameColumn(name: "ScheduledDate", table: "ScheduledActions", newName: "FechaProgramada");
            migrationBuilder.RenameColumn(name: "Status", table: "ScheduledActions", newName: "Estado");
            migrationBuilder.RenameColumn(name: "KaizenReviewId", table: "PlanAdjustments", newName: "RevisionKaizenId");
            migrationBuilder.RenameColumn(name: "ActionPlanItemId", table: "PlanAdjustments", newName: "AccionPlanificadaId");
            migrationBuilder.RenameColumn(name: "NewActionPlanItemId", table: "PlanAdjustments", newName: "NuevaAccionPlanificadaId");
            migrationBuilder.RenameColumn(name: "Type", table: "PlanAdjustments", newName: "Tipo");
            migrationBuilder.RenameColumn(name: "Description", table: "PlanAdjustments", newName: "Descripcion");
            migrationBuilder.RenameColumn(name: "CreatedAt", table: "PlanAdjustments", newName: "FechaCreacion");
            migrationBuilder.RenameColumn(name: "EffectiveDate", table: "PlanAdjustments", newName: "FechaVigencia");
            migrationBuilder.RenameColumn(name: "NewValues", table: "PlanAdjustments", newName: "ValoresNuevos");
            migrationBuilder.RenameColumn(name: "PreviousValues", table: "PlanAdjustments", newName: "ValoresAnteriores");
            migrationBuilder.RenameColumn(name: "Reason", table: "PlanAdjustments", newName: "Motivo");
            migrationBuilder.RenameColumn(name: "ResumeDate", table: "PlanAdjustments", newName: "FechaReanudacion");
            migrationBuilder.RenameColumn(name: "Name", table: "PersonalAreas", newName: "Nombre");
            migrationBuilder.RenameColumn(name: "GoalId", table: "KaizenReviews", newName: "MetaId");
            migrationBuilder.RenameColumn(name: "PeriodStart", table: "KaizenReviews", newName: "InicioPeriodo");
            migrationBuilder.RenameColumn(name: "PeriodEnd", table: "KaizenReviews", newName: "FinPeriodo");
            migrationBuilder.RenameColumn(name: "CompletionPercentage", table: "KaizenReviews", newName: "PorcentajeCumplimiento");
            migrationBuilder.RenameColumn(name: "WhatWorked", table: "KaizenReviews", newName: "QueFunciono");
            migrationBuilder.RenameColumn(name: "WhatHindered", table: "KaizenReviews", newName: "QueDificulto");
            migrationBuilder.RenameColumn(name: "WasTooDifficult", table: "KaizenReviews", newName: "FueDemasiadoDificil");
            migrationBuilder.RenameColumn(name: "SmallAdjustment", table: "KaizenReviews", newName: "AjustePequeno");
            migrationBuilder.RenameColumn(name: "AutomaticSuggestion", table: "KaizenReviews", newName: "SugerenciaAutomatica");
            migrationBuilder.RenameColumn(name: "CreatedAt", table: "KaizenReviews", newName: "FechaCreacion");
            migrationBuilder.RenameColumn(name: "AdditionalNotes", table: "KaizenReviews", newName: "NotasAdicionales");
            migrationBuilder.RenameColumn(name: "GoalStatusAtEnd", table: "KaizenReviews", newName: "EstadoMetaFinal");
            migrationBuilder.RenameColumn(name: "GoalStatusAtStart", table: "KaizenReviews", newName: "EstadoMetaInicial");
            migrationBuilder.RenameColumn(name: "Learned", table: "KaizenReviews", newName: "Aprendizaje");
            migrationBuilder.RenameColumn(name: "NextPeriodChange", table: "KaizenReviews", newName: "CambioProximoPeriodo");
            migrationBuilder.RenameColumn(name: "NextReviewDate", table: "KaizenReviews", newName: "FechaProximaRevision");
            migrationBuilder.RenameColumn(name: "GoalId", table: "KaizenAssessments", newName: "MetaId");
            migrationBuilder.RenameColumn(name: "WhereAmI", table: "KaizenAssessments", newName: "DondeEstoy");
            migrationBuilder.RenameColumn(name: "WhatToChange", table: "KaizenAssessments", newName: "QueCambiar");
            migrationBuilder.RenameColumn(name: "Obstacles", table: "KaizenAssessments", newName: "Obstaculos");
            migrationBuilder.RenameColumn(name: "WhatWorks", table: "KaizenAssessments", newName: "QueFunciona");
            migrationBuilder.RenameColumn(name: "SmallestImprovement", table: "KaizenAssessments", newName: "MejoraMasPequena");
            migrationBuilder.RenameColumn(name: "ImprovementEvidence", table: "KaizenAssessments", newName: "EvidenciaMejora");
            migrationBuilder.RenameColumn(name: "PerceivedDifficulty", table: "KaizenAssessments", newName: "DificultadPercibida");
            migrationBuilder.RenameColumn(name: "CreatedAt", table: "KaizenAssessments", newName: "FechaCreacion");
            migrationBuilder.RenameColumn(name: "Title", table: "Goals", newName: "Titulo");
            migrationBuilder.RenameColumn(name: "Description", table: "Goals", newName: "Descripcion");
            migrationBuilder.RenameColumn(name: "PersonalAreaId", table: "Goals", newName: "AreaPersonalId");
            migrationBuilder.RenameColumn(name: "WhyImportant", table: "Goals", newName: "PorQueEsImportante");
            migrationBuilder.RenameColumn(name: "CurrentSituation", table: "Goals", newName: "SituacionActual");
            migrationBuilder.RenameColumn(name: "ExpectedOutcome", table: "Goals", newName: "ResultadoEsperado");
            migrationBuilder.RenameColumn(name: "StartDate", table: "Goals", newName: "FechaInicio");
            migrationBuilder.RenameColumn(name: "TargetDate", table: "Goals", newName: "FechaObjetivo");
            migrationBuilder.RenameColumn(name: "ProgressMetric", table: "Goals", newName: "MetricaProgreso");
            migrationBuilder.RenameColumn(name: "Status", table: "Goals", newName: "Estado");
            migrationBuilder.RenameColumn(name: "ReviewFrequency", table: "Goals", newName: "FrecuenciaRevision");
            migrationBuilder.RenameColumn(name: "NextReviewDate", table: "Goals", newName: "FechaProximaRevision");
            migrationBuilder.RenameColumn(name: "ActivatedAt", table: "Goals", newName: "FechaActivacion");
            migrationBuilder.RenameColumn(name: "CreatedAt", table: "Goals", newName: "FechaCreacion");
            migrationBuilder.RenameColumn(name: "ArchiveReason", table: "Goals", newName: "MotivoArchivo");
            migrationBuilder.RenameColumn(name: "ArchivedAt", table: "Goals", newName: "FechaArchivo");
            migrationBuilder.RenameColumn(name: "GoalId", table: "GoalHistoryEvents", newName: "MetaId");
            migrationBuilder.RenameColumn(name: "ActionPlanItemId", table: "GoalHistoryEvents", newName: "AccionPlanificadaId");
            migrationBuilder.RenameColumn(name: "KaizenReviewId", table: "GoalHistoryEvents", newName: "RevisionKaizenId");
            migrationBuilder.RenameColumn(name: "Type", table: "GoalHistoryEvents", newName: "Tipo");
            migrationBuilder.RenameColumn(name: "Description", table: "GoalHistoryEvents", newName: "Descripcion");
            migrationBuilder.RenameColumn(name: "PreviousValues", table: "GoalHistoryEvents", newName: "ValoresAnteriores");
            migrationBuilder.RenameColumn(name: "NewValues", table: "GoalHistoryEvents", newName: "ValoresNuevos");
            migrationBuilder.RenameColumn(name: "Reason", table: "GoalHistoryEvents", newName: "Motivo");
            migrationBuilder.RenameColumn(name: "OccurredAt", table: "GoalHistoryEvents", newName: "FechaOcurrencia");
            migrationBuilder.RenameColumn(name: "GoalId", table: "ActionPlanItems", newName: "MetaId");
            migrationBuilder.RenameColumn(name: "Name", table: "ActionPlanItems", newName: "Nombre");
            migrationBuilder.RenameColumn(name: "Description", table: "ActionPlanItems", newName: "Descripcion");
            migrationBuilder.RenameColumn(name: "Frequency", table: "ActionPlanItems", newName: "Frecuencia");
            migrationBuilder.RenameColumn(name: "Weekdays", table: "ActionPlanItems", newName: "DiasSemana");
            migrationBuilder.RenameColumn(name: "Time", table: "ActionPlanItems", newName: "Hora");
            migrationBuilder.RenameColumn(name: "StartDate", table: "ActionPlanItems", newName: "FechaInicio");
            migrationBuilder.RenameColumn(name: "EndDate", table: "ActionPlanItems", newName: "FechaFin");
            migrationBuilder.RenameColumn(name: "EstimatedDifficulty", table: "ActionPlanItems", newName: "DificultadEstimada");
            migrationBuilder.RenameColumn(name: "TargetAmount", table: "ActionPlanItems", newName: "CantidadObjetivo");
            migrationBuilder.RenameColumn(name: "MetricUnit", table: "ActionPlanItems", newName: "UnidadMetrica");
            migrationBuilder.RenameColumn(name: "Status", table: "ActionPlanItems", newName: "Estado");
            migrationBuilder.RenameColumn(name: "ActionSeriesId", table: "ActionPlanItems", newName: "SerieAccionId");
            migrationBuilder.RenameColumn(name: "ChangeReason", table: "ActionPlanItems", newName: "MotivoCambio");
            migrationBuilder.RenameColumn(name: "EffectiveFrom", table: "ActionPlanItems", newName: "VigenteDesde");
            migrationBuilder.RenameColumn(name: "EffectiveTo", table: "ActionPlanItems", newName: "VigenteHasta");
            migrationBuilder.RenameColumn(name: "OriginReviewId", table: "ActionPlanItems", newName: "RevisionOrigenId");
            migrationBuilder.RenameColumn(name: "PreviousVersionId", table: "ActionPlanItems", newName: "VersionAnteriorId");
            migrationBuilder.RenameColumn(name: "ArchiveReason", table: "ActionPlanItems", newName: "MotivoArchivo");
            migrationBuilder.RenameColumn(name: "ArchivedAt", table: "ActionPlanItems", newName: "FechaArchivo");
            migrationBuilder.RenameColumn(name: "ScheduledActionId", table: "ActionLogs", newName: "AccionProgramadaId");
            migrationBuilder.RenameColumn(name: "Status", table: "ActionLogs", newName: "Estado");
            migrationBuilder.RenameColumn(name: "Note", table: "ActionLogs", newName: "Nota");
            migrationBuilder.RenameColumn(name: "ActualValue", table: "ActionLogs", newName: "ValorReal");
            migrationBuilder.RenameColumn(name: "LoggedAt", table: "ActionLogs", newName: "FechaRegistro");
            migrationBuilder.RenameTable(name: "ScheduledActions", newName: "AccionProgramada");
            migrationBuilder.RenameTable(name: "PlanAdjustments", newName: "AjustePlan");
            migrationBuilder.RenameTable(name: "PersonalAreas", newName: "AreaPersonal");
            migrationBuilder.RenameTable(name: "KaizenReviews", newName: "RevisionKaizen");
            migrationBuilder.RenameTable(name: "KaizenAssessments", newName: "EvaluacionKaizen");
            migrationBuilder.RenameTable(name: "Goals", newName: "Meta");
            migrationBuilder.RenameTable(name: "GoalHistoryEvents", newName: "EventoHistorialMeta");
            migrationBuilder.RenameTable(name: "ActionPlanItems", newName: "AccionPlanificada");
            migrationBuilder.RenameTable(name: "ActionLogs", newName: "RegistroAccion");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_ActionLogs]', N'PK_RegistroAccion', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_ActionPlanItems]', N'PK_AccionPlanificada', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_GoalHistoryEvents]', N'PK_EventoHistorialMeta', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_Goals]', N'PK_Meta', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_KaizenAssessments]', N'PK_EvaluacionKaizen', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_KaizenReviews]', N'PK_RevisionKaizen', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_PersonalAreas]', N'PK_AreaPersonal', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_PlanAdjustments]', N'PK_AjustePlan', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_ScheduledActions]', N'PK_AccionProgramada', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_ActionLogs_ScheduledActions_ScheduledActionId]', N'FK_RegistroAccion_AccionProgramada_AccionProgramadaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_ActionPlanItems_ActionPlanItems_PreviousVersionId]', N'FK_AccionPlanificada_AccionPlanificada_VersionAnteriorId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_ActionPlanItems_Goals_GoalId]', N'FK_AccionPlanificada_Meta_MetaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_ActionPlanItems_KaizenReviews_OriginReviewId]', N'FK_AccionPlanificada_RevisionKaizen_RevisionOrigenId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_GoalHistoryEvents_ActionPlanItems_ActionPlanItemId]', N'FK_EventoHistorialMeta_AccionPlanificada_AccionPlanificadaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_GoalHistoryEvents_Goals_GoalId]', N'FK_EventoHistorialMeta_Meta_MetaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_GoalHistoryEvents_KaizenReviews_KaizenReviewId]', N'FK_EventoHistorialMeta_RevisionKaizen_RevisionKaizenId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_Goals_PersonalAreas_PersonalAreaId]', N'FK_Meta_AreaPersonal_AreaPersonalId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_KaizenAssessments_Goals_GoalId]', N'FK_EvaluacionKaizen_Meta_MetaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_KaizenReviews_Goals_GoalId]', N'FK_RevisionKaizen_Meta_MetaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_PlanAdjustments_ActionPlanItems_ActionPlanItemId]', N'FK_AjustePlan_AccionPlanificada_AccionPlanificadaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_PlanAdjustments_ActionPlanItems_NewActionPlanItemId]', N'FK_AjustePlan_AccionPlanificada_NuevaAccionPlanificadaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_PlanAdjustments_KaizenReviews_KaizenReviewId]', N'FK_AjustePlan_RevisionKaizen_RevisionKaizenId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_ScheduledActions_ActionPlanItems_ActionPlanItemId]', N'FK_AccionProgramada_AccionPlanificada_AccionPlanificadaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[RegistroAccion].[IX_ActionLogs_ScheduledActionId]', N'IX_RegistroAccion_AccionProgramadaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_ActionPlanItems_ActionSeriesId_EffectiveFrom]', N'IX_AccionPlanificada_SerieAccionId_VigenteDesde', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_ActionPlanItems_GoalId]', N'IX_AccionPlanificada_MetaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_ActionPlanItems_OriginReviewId]', N'IX_AccionPlanificada_RevisionOrigenId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_ActionPlanItems_PreviousVersionId]', N'IX_AccionPlanificada_VersionAnteriorId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_GoalHistoryEvents_ActionPlanItemId]', N'IX_EventoHistorialMeta_AccionPlanificadaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_GoalHistoryEvents_GoalId_OccurredAt]', N'IX_EventoHistorialMeta_MetaId_FechaOcurrencia', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_GoalHistoryEvents_KaizenReviewId]', N'IX_EventoHistorialMeta_RevisionKaizenId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[Meta].[IX_Goals_PersonalAreaId]', N'IX_Meta_AreaPersonalId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EvaluacionKaizen].[IX_KaizenAssessments_GoalId]', N'IX_EvaluacionKaizen_MetaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[RevisionKaizen].[IX_KaizenReviews_GoalId_PeriodStart_PeriodEnd]', N'IX_RevisionKaizen_MetaId_InicioPeriodo_FinPeriodo', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_PlanAdjustments_ActionPlanItemId]', N'IX_AjustePlan_AccionPlanificadaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_PlanAdjustments_KaizenReviewId]', N'IX_AjustePlan_RevisionKaizenId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_PlanAdjustments_NewActionPlanItemId]', N'IX_AjustePlan_NuevaAccionPlanificadaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionProgramada].[IX_ScheduledActions_ActionPlanItemId_ScheduledDate]', N'IX_AccionProgramada_AccionPlanificadaId_FechaProgramada', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionProgramada].[IX_ScheduledActions_ScheduledDate]', N'IX_AccionProgramada_FechaProgramada', N'INDEX';");
    }

    protected override void Down(MigrationBuilder migrationBuilder)
    {
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[RegistroAccion].[IX_RegistroAccion_AccionProgramadaId]', N'IX_ActionLogs_ScheduledActionId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_AccionPlanificada_SerieAccionId_VigenteDesde]', N'IX_ActionPlanItems_ActionSeriesId_EffectiveFrom', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_AccionPlanificada_MetaId]', N'IX_ActionPlanItems_GoalId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_AccionPlanificada_RevisionOrigenId]', N'IX_ActionPlanItems_OriginReviewId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionPlanificada].[IX_AccionPlanificada_VersionAnteriorId]', N'IX_ActionPlanItems_PreviousVersionId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_EventoHistorialMeta_AccionPlanificadaId]', N'IX_GoalHistoryEvents_ActionPlanItemId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_EventoHistorialMeta_MetaId_FechaOcurrencia]', N'IX_GoalHistoryEvents_GoalId_OccurredAt', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EventoHistorialMeta].[IX_EventoHistorialMeta_RevisionKaizenId]', N'IX_GoalHistoryEvents_KaizenReviewId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[Meta].[IX_Meta_AreaPersonalId]', N'IX_Goals_PersonalAreaId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[EvaluacionKaizen].[IX_EvaluacionKaizen_MetaId]', N'IX_KaizenAssessments_GoalId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[RevisionKaizen].[IX_RevisionKaizen_MetaId_InicioPeriodo_FinPeriodo]', N'IX_KaizenReviews_GoalId_PeriodStart_PeriodEnd', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_AjustePlan_AccionPlanificadaId]', N'IX_PlanAdjustments_ActionPlanItemId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_AjustePlan_RevisionKaizenId]', N'IX_PlanAdjustments_KaizenReviewId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AjustePlan].[IX_AjustePlan_NuevaAccionPlanificadaId]', N'IX_PlanAdjustments_NewActionPlanItemId', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionProgramada].[IX_AccionProgramada_AccionPlanificadaId_FechaProgramada]', N'IX_ScheduledActions_ActionPlanItemId_ScheduledDate', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[AccionProgramada].[IX_AccionProgramada_FechaProgramada]', N'IX_ScheduledActions_ScheduledDate', N'INDEX';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_RegistroAccion_AccionProgramada_AccionProgramadaId]', N'FK_ActionLogs_ScheduledActions_ScheduledActionId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AccionPlanificada_AccionPlanificada_VersionAnteriorId]', N'FK_ActionPlanItems_ActionPlanItems_PreviousVersionId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AccionPlanificada_Meta_MetaId]', N'FK_ActionPlanItems_Goals_GoalId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AccionPlanificada_RevisionKaizen_RevisionOrigenId]', N'FK_ActionPlanItems_KaizenReviews_OriginReviewId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_EventoHistorialMeta_AccionPlanificada_AccionPlanificadaId]', N'FK_GoalHistoryEvents_ActionPlanItems_ActionPlanItemId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_EventoHistorialMeta_Meta_MetaId]', N'FK_GoalHistoryEvents_Goals_GoalId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_EventoHistorialMeta_RevisionKaizen_RevisionKaizenId]', N'FK_GoalHistoryEvents_KaizenReviews_KaizenReviewId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_Meta_AreaPersonal_AreaPersonalId]', N'FK_Goals_PersonalAreas_PersonalAreaId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_EvaluacionKaizen_Meta_MetaId]', N'FK_KaizenAssessments_Goals_GoalId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_RevisionKaizen_Meta_MetaId]', N'FK_KaizenReviews_Goals_GoalId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AjustePlan_AccionPlanificada_AccionPlanificadaId]', N'FK_PlanAdjustments_ActionPlanItems_ActionPlanItemId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AjustePlan_AccionPlanificada_NuevaAccionPlanificadaId]', N'FK_PlanAdjustments_ActionPlanItems_NewActionPlanItemId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AjustePlan_RevisionKaizen_RevisionKaizenId]', N'FK_PlanAdjustments_KaizenReviews_KaizenReviewId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[FK_AccionProgramada_AccionPlanificada_AccionPlanificadaId]', N'FK_ScheduledActions_ActionPlanItems_ActionPlanItemId', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_RegistroAccion]', N'PK_ActionLogs', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_AccionPlanificada]', N'PK_ActionPlanItems', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_EventoHistorialMeta]', N'PK_GoalHistoryEvents', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_Meta]', N'PK_Goals', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_EvaluacionKaizen]', N'PK_KaizenAssessments', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_RevisionKaizen]', N'PK_KaizenReviews', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_AreaPersonal]', N'PK_PersonalAreas', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_AjustePlan]', N'PK_PlanAdjustments', N'OBJECT';");
            migrationBuilder.Sql("EXEC sp_rename N'[dbo].[PK_AccionProgramada]', N'PK_ScheduledActions', N'OBJECT';");
            migrationBuilder.RenameColumn(name: "AccionPlanificadaId", table: "AccionProgramada", newName: "ActionPlanItemId");
            migrationBuilder.RenameColumn(name: "FechaProgramada", table: "AccionProgramada", newName: "ScheduledDate");
            migrationBuilder.RenameColumn(name: "Estado", table: "AccionProgramada", newName: "Status");
            migrationBuilder.RenameColumn(name: "RevisionKaizenId", table: "AjustePlan", newName: "KaizenReviewId");
            migrationBuilder.RenameColumn(name: "AccionPlanificadaId", table: "AjustePlan", newName: "ActionPlanItemId");
            migrationBuilder.RenameColumn(name: "NuevaAccionPlanificadaId", table: "AjustePlan", newName: "NewActionPlanItemId");
            migrationBuilder.RenameColumn(name: "Tipo", table: "AjustePlan", newName: "Type");
            migrationBuilder.RenameColumn(name: "Descripcion", table: "AjustePlan", newName: "Description");
            migrationBuilder.RenameColumn(name: "FechaCreacion", table: "AjustePlan", newName: "CreatedAt");
            migrationBuilder.RenameColumn(name: "FechaVigencia", table: "AjustePlan", newName: "EffectiveDate");
            migrationBuilder.RenameColumn(name: "ValoresNuevos", table: "AjustePlan", newName: "NewValues");
            migrationBuilder.RenameColumn(name: "ValoresAnteriores", table: "AjustePlan", newName: "PreviousValues");
            migrationBuilder.RenameColumn(name: "Motivo", table: "AjustePlan", newName: "Reason");
            migrationBuilder.RenameColumn(name: "FechaReanudacion", table: "AjustePlan", newName: "ResumeDate");
            migrationBuilder.RenameColumn(name: "Nombre", table: "AreaPersonal", newName: "Name");
            migrationBuilder.RenameColumn(name: "MetaId", table: "RevisionKaizen", newName: "GoalId");
            migrationBuilder.RenameColumn(name: "InicioPeriodo", table: "RevisionKaizen", newName: "PeriodStart");
            migrationBuilder.RenameColumn(name: "FinPeriodo", table: "RevisionKaizen", newName: "PeriodEnd");
            migrationBuilder.RenameColumn(name: "PorcentajeCumplimiento", table: "RevisionKaizen", newName: "CompletionPercentage");
            migrationBuilder.RenameColumn(name: "QueFunciono", table: "RevisionKaizen", newName: "WhatWorked");
            migrationBuilder.RenameColumn(name: "QueDificulto", table: "RevisionKaizen", newName: "WhatHindered");
            migrationBuilder.RenameColumn(name: "FueDemasiadoDificil", table: "RevisionKaizen", newName: "WasTooDifficult");
            migrationBuilder.RenameColumn(name: "AjustePequeno", table: "RevisionKaizen", newName: "SmallAdjustment");
            migrationBuilder.RenameColumn(name: "SugerenciaAutomatica", table: "RevisionKaizen", newName: "AutomaticSuggestion");
            migrationBuilder.RenameColumn(name: "FechaCreacion", table: "RevisionKaizen", newName: "CreatedAt");
            migrationBuilder.RenameColumn(name: "NotasAdicionales", table: "RevisionKaizen", newName: "AdditionalNotes");
            migrationBuilder.RenameColumn(name: "EstadoMetaFinal", table: "RevisionKaizen", newName: "GoalStatusAtEnd");
            migrationBuilder.RenameColumn(name: "EstadoMetaInicial", table: "RevisionKaizen", newName: "GoalStatusAtStart");
            migrationBuilder.RenameColumn(name: "Aprendizaje", table: "RevisionKaizen", newName: "Learned");
            migrationBuilder.RenameColumn(name: "CambioProximoPeriodo", table: "RevisionKaizen", newName: "NextPeriodChange");
            migrationBuilder.RenameColumn(name: "FechaProximaRevision", table: "RevisionKaizen", newName: "NextReviewDate");
            migrationBuilder.RenameColumn(name: "MetaId", table: "EvaluacionKaizen", newName: "GoalId");
            migrationBuilder.RenameColumn(name: "DondeEstoy", table: "EvaluacionKaizen", newName: "WhereAmI");
            migrationBuilder.RenameColumn(name: "QueCambiar", table: "EvaluacionKaizen", newName: "WhatToChange");
            migrationBuilder.RenameColumn(name: "Obstaculos", table: "EvaluacionKaizen", newName: "Obstacles");
            migrationBuilder.RenameColumn(name: "QueFunciona", table: "EvaluacionKaizen", newName: "WhatWorks");
            migrationBuilder.RenameColumn(name: "MejoraMasPequena", table: "EvaluacionKaizen", newName: "SmallestImprovement");
            migrationBuilder.RenameColumn(name: "EvidenciaMejora", table: "EvaluacionKaizen", newName: "ImprovementEvidence");
            migrationBuilder.RenameColumn(name: "DificultadPercibida", table: "EvaluacionKaizen", newName: "PerceivedDifficulty");
            migrationBuilder.RenameColumn(name: "FechaCreacion", table: "EvaluacionKaizen", newName: "CreatedAt");
            migrationBuilder.RenameColumn(name: "Titulo", table: "Meta", newName: "Title");
            migrationBuilder.RenameColumn(name: "Descripcion", table: "Meta", newName: "Description");
            migrationBuilder.RenameColumn(name: "AreaPersonalId", table: "Meta", newName: "PersonalAreaId");
            migrationBuilder.RenameColumn(name: "PorQueEsImportante", table: "Meta", newName: "WhyImportant");
            migrationBuilder.RenameColumn(name: "SituacionActual", table: "Meta", newName: "CurrentSituation");
            migrationBuilder.RenameColumn(name: "ResultadoEsperado", table: "Meta", newName: "ExpectedOutcome");
            migrationBuilder.RenameColumn(name: "FechaInicio", table: "Meta", newName: "StartDate");
            migrationBuilder.RenameColumn(name: "FechaObjetivo", table: "Meta", newName: "TargetDate");
            migrationBuilder.RenameColumn(name: "MetricaProgreso", table: "Meta", newName: "ProgressMetric");
            migrationBuilder.RenameColumn(name: "Estado", table: "Meta", newName: "Status");
            migrationBuilder.RenameColumn(name: "FrecuenciaRevision", table: "Meta", newName: "ReviewFrequency");
            migrationBuilder.RenameColumn(name: "FechaProximaRevision", table: "Meta", newName: "NextReviewDate");
            migrationBuilder.RenameColumn(name: "FechaActivacion", table: "Meta", newName: "ActivatedAt");
            migrationBuilder.RenameColumn(name: "FechaCreacion", table: "Meta", newName: "CreatedAt");
            migrationBuilder.RenameColumn(name: "MotivoArchivo", table: "Meta", newName: "ArchiveReason");
            migrationBuilder.RenameColumn(name: "FechaArchivo", table: "Meta", newName: "ArchivedAt");
            migrationBuilder.RenameColumn(name: "MetaId", table: "EventoHistorialMeta", newName: "GoalId");
            migrationBuilder.RenameColumn(name: "AccionPlanificadaId", table: "EventoHistorialMeta", newName: "ActionPlanItemId");
            migrationBuilder.RenameColumn(name: "RevisionKaizenId", table: "EventoHistorialMeta", newName: "KaizenReviewId");
            migrationBuilder.RenameColumn(name: "Tipo", table: "EventoHistorialMeta", newName: "Type");
            migrationBuilder.RenameColumn(name: "Descripcion", table: "EventoHistorialMeta", newName: "Description");
            migrationBuilder.RenameColumn(name: "ValoresAnteriores", table: "EventoHistorialMeta", newName: "PreviousValues");
            migrationBuilder.RenameColumn(name: "ValoresNuevos", table: "EventoHistorialMeta", newName: "NewValues");
            migrationBuilder.RenameColumn(name: "Motivo", table: "EventoHistorialMeta", newName: "Reason");
            migrationBuilder.RenameColumn(name: "FechaOcurrencia", table: "EventoHistorialMeta", newName: "OccurredAt");
            migrationBuilder.RenameColumn(name: "MetaId", table: "AccionPlanificada", newName: "GoalId");
            migrationBuilder.RenameColumn(name: "Nombre", table: "AccionPlanificada", newName: "Name");
            migrationBuilder.RenameColumn(name: "Descripcion", table: "AccionPlanificada", newName: "Description");
            migrationBuilder.RenameColumn(name: "Frecuencia", table: "AccionPlanificada", newName: "Frequency");
            migrationBuilder.RenameColumn(name: "DiasSemana", table: "AccionPlanificada", newName: "Weekdays");
            migrationBuilder.RenameColumn(name: "Hora", table: "AccionPlanificada", newName: "Time");
            migrationBuilder.RenameColumn(name: "FechaInicio", table: "AccionPlanificada", newName: "StartDate");
            migrationBuilder.RenameColumn(name: "FechaFin", table: "AccionPlanificada", newName: "EndDate");
            migrationBuilder.RenameColumn(name: "DificultadEstimada", table: "AccionPlanificada", newName: "EstimatedDifficulty");
            migrationBuilder.RenameColumn(name: "CantidadObjetivo", table: "AccionPlanificada", newName: "TargetAmount");
            migrationBuilder.RenameColumn(name: "UnidadMetrica", table: "AccionPlanificada", newName: "MetricUnit");
            migrationBuilder.RenameColumn(name: "Estado", table: "AccionPlanificada", newName: "Status");
            migrationBuilder.RenameColumn(name: "SerieAccionId", table: "AccionPlanificada", newName: "ActionSeriesId");
            migrationBuilder.RenameColumn(name: "MotivoCambio", table: "AccionPlanificada", newName: "ChangeReason");
            migrationBuilder.RenameColumn(name: "VigenteDesde", table: "AccionPlanificada", newName: "EffectiveFrom");
            migrationBuilder.RenameColumn(name: "VigenteHasta", table: "AccionPlanificada", newName: "EffectiveTo");
            migrationBuilder.RenameColumn(name: "RevisionOrigenId", table: "AccionPlanificada", newName: "OriginReviewId");
            migrationBuilder.RenameColumn(name: "VersionAnteriorId", table: "AccionPlanificada", newName: "PreviousVersionId");
            migrationBuilder.RenameColumn(name: "MotivoArchivo", table: "AccionPlanificada", newName: "ArchiveReason");
            migrationBuilder.RenameColumn(name: "FechaArchivo", table: "AccionPlanificada", newName: "ArchivedAt");
            migrationBuilder.RenameColumn(name: "AccionProgramadaId", table: "RegistroAccion", newName: "ScheduledActionId");
            migrationBuilder.RenameColumn(name: "Estado", table: "RegistroAccion", newName: "Status");
            migrationBuilder.RenameColumn(name: "Nota", table: "RegistroAccion", newName: "Note");
            migrationBuilder.RenameColumn(name: "ValorReal", table: "RegistroAccion", newName: "ActualValue");
            migrationBuilder.RenameColumn(name: "FechaRegistro", table: "RegistroAccion", newName: "LoggedAt");
            migrationBuilder.RenameTable(name: "AccionProgramada", newName: "ScheduledActions");
            migrationBuilder.RenameTable(name: "AjustePlan", newName: "PlanAdjustments");
            migrationBuilder.RenameTable(name: "AreaPersonal", newName: "PersonalAreas");
            migrationBuilder.RenameTable(name: "RevisionKaizen", newName: "KaizenReviews");
            migrationBuilder.RenameTable(name: "EvaluacionKaizen", newName: "KaizenAssessments");
            migrationBuilder.RenameTable(name: "Meta", newName: "Goals");
            migrationBuilder.RenameTable(name: "EventoHistorialMeta", newName: "GoalHistoryEvents");
            migrationBuilder.RenameTable(name: "AccionPlanificada", newName: "ActionPlanItems");
            migrationBuilder.RenameTable(name: "RegistroAccion", newName: "ActionLogs");
    }
}
