// <auto-generated />
using System;
using Kaizen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaizen.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260803145957_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kaizen.Domain.Entities.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ActualValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LoggedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ScheduledActionId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScheduledActionId")
                        .IsUnique();

                    b.ToTable("ActionLogs");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ActionPlanItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int>("EstimatedDifficulty")
                        .HasColumnType("int");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("MetricUnit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TargetAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("Time")
                        .HasColumnType("time");

                    b.Property<string>("Weekdays")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("ActionPlanItems");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Goal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentSituation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedOutcome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NextReviewDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonalAreaId")
                        .HasColumnType("int");

                    b.Property<string>("ProgressMetric")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReviewFrequency")
                        .HasColumnType("int");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("TargetDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhyImportant")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PersonalAreaId");

                    b.ToTable("Goals");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.KaizenAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<string>("ImprovementEvidence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obstacles")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PerceivedDifficulty")
                        .HasColumnType("int");

                    b.Property<string>("SmallestImprovement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatToChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWorks")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhereAmI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId")
                        .IsUnique();

                    b.ToTable("KaizenAssessments");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.KaizenReview", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutomaticSuggestion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CompletionPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GoalId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PeriodEnd")
                        .HasColumnType("date");

                    b.Property<DateOnly>("PeriodStart")
                        .HasColumnType("date");

                    b.Property<string>("SmallAdjustment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WasTooDifficult")
                        .HasColumnType("bit");

                    b.Property<string>("WhatHindered")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WhatWorked")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("KaizenReviews");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.PersonalArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonalAreas");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.PlanAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActionPlanItemId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KaizenReviewId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionPlanItemId");

                    b.HasIndex("KaizenReviewId");

                    b.ToTable("PlanAdjustments");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ScheduledAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ActionPlanItemId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("ScheduledDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActionPlanItemId", "ScheduledDate")
                        .IsUnique();

                    b.ToTable("ScheduledActions");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ActionLog", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.ScheduledAction", "ScheduledAction")
                        .WithOne("Log")
                        .HasForeignKey("Kaizen.Domain.Entities.ActionLog", "ScheduledActionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScheduledAction");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ActionPlanItem", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Goal", "Goal")
                        .WithMany("Actions")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Goal", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.PersonalArea", "PersonalArea")
                        .WithMany("Goals")
                        .HasForeignKey("PersonalAreaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonalArea");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.KaizenAssessment", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Goal", "Goal")
                        .WithOne("Assessment")
                        .HasForeignKey("Kaizen.Domain.Entities.KaizenAssessment", "GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.KaizenReview", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Goal", "Goal")
                        .WithMany("Reviews")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.PlanAdjustment", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.ActionPlanItem", "ActionPlanItem")
                        .WithMany()
                        .HasForeignKey("ActionPlanItemId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.Entities.KaizenReview", "KaizenReview")
                        .WithMany("Adjustments")
                        .HasForeignKey("KaizenReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionPlanItem");

                    b.Navigation("KaizenReview");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ScheduledAction", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.ActionPlanItem", "ActionPlanItem")
                        .WithMany("ScheduledActions")
                        .HasForeignKey("ActionPlanItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActionPlanItem");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ActionPlanItem", b =>
                {
                    b.Navigation("ScheduledActions");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Goal", b =>
                {
                    b.Navigation("Actions");

                    b.Navigation("Assessment");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.KaizenReview", b =>
                {
                    b.Navigation("Adjustments");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.PersonalArea", b =>
                {
                    b.Navigation("Goals");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.ScheduledAction", b =>
                {
                    b.Navigation("Log");
                });
#pragma warning restore 612, 618
        }
    }
}

