// <auto-generated />
using System;
using Kaizen.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaizen.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260821190620_NombresDominioEnEspanol")]
    partial class NombresDominioEnEspanol
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionPlanificada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("CantidadObjetivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DiasSemana")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DificultadEstimada")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaArchivo")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("int");

                    b.Property<TimeOnly?>("Hora")
                        .HasColumnType("time");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("MotivoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoCambio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisionOrigenId")
                        .HasColumnType("int");

                    b.Property<Guid>("SerieAccionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UnidadMetrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<int?>("VersionAnteriorId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("VigenteDesde")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("VigenteHasta")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.HasIndex("RevisionOrigenId");

                    b.HasIndex("VersionAnteriorId");

                    b.HasIndex("SerieAccionId", "VigenteDesde");

                    b.ToTable("AccionPlanificada", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionProgramada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("FechaProgramada");

                    b.HasIndex("AccionPlanificadaId", "FechaProgramada")
                        .IsUnique();

                    b.ToTable("AccionProgramada", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AjustePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("FechaReanudacion")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FechaVigencia")
                        .HasColumnType("date");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NuevaAccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<int>("RevisionKaizenId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccionPlanificadaId");

                    b.HasIndex("NuevaAccionPlanificadaId");

                    b.HasIndex("RevisionKaizenId");

                    b.ToTable("AjustePlan", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AreaPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreaPersonal", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.EvaluacionKaizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DificultadPercibida")
                        .HasColumnType("int");

                    b.Property<string>("DondeEstoy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EvidenciaMejora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("MejoraMasPequena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("Obstaculos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueCambiar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueFunciona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId")
                        .IsUnique();

                    b.ToTable("EvaluacionKaizen", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.EventoHistorialMeta", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int?>("AccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaOcurrencia")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RevisionKaizenId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<string>("ValoresAnteriores")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ValoresNuevos")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccionPlanificadaId");

                    b.HasIndex("RevisionKaizenId");

                    b.HasIndex("MetaId", "FechaOcurrencia");

                    b.ToTable("EventoHistorialMeta", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AreaPersonalId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaActivacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaArchivo")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("FechaProximaRevision")
                        .HasColumnType("date");

                    b.Property<int>("FrecuenciaRevision")
                        .HasColumnType("int");

                    b.Property<string>("MetricaProgreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoArchivo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorQueEsImportante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoEsperado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SituacionActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaPersonalId");

                    b.ToTable("Meta", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.RegistroAccion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionProgramadaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ValorReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("AccionProgramadaId")
                        .IsUnique();

                    b.ToTable("RegistroAccion", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.RevisionKaizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AjustePequeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Aprendizaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CambioProximoPeriodo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EstadoMetaFinal")
                        .HasColumnType("int");

                    b.Property<int>("EstadoMetaInicial")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("FechaProximaRevision")
                        .HasColumnType("date");

                    b.Property<DateOnly>("FinPeriodo")
                        .HasColumnType("date");

                    b.Property<bool>("FueDemasiadoDificil")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("InicioPeriodo")
                        .HasColumnType("date");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("NotasAdicionales")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeCumplimiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("QueDificulto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueFunciono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SugerenciaAutomatica")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId", "InicioPeriodo", "FinPeriodo")
                        .IsUnique();

                    b.ToTable("RevisionKaizen", (string)null);
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionPlanificada", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Meta", "Meta")
                        .WithMany("Acciones")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Domain.Entities.RevisionKaizen", "RevisionOrigen")
                        .WithMany()
                        .HasForeignKey("RevisionOrigenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.Entities.AccionPlanificada", "VersionAnterior")
                        .WithMany()
                        .HasForeignKey("VersionAnteriorId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Meta");

                    b.Navigation("RevisionOrigen");

                    b.Navigation("VersionAnterior");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionProgramada", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.AccionPlanificada", "AccionPlanificada")
                        .WithMany("AccionesProgramadas")
                        .HasForeignKey("AccionPlanificadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionPlanificada");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AjustePlan", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.AccionPlanificada", "AccionPlanificada")
                        .WithMany()
                        .HasForeignKey("AccionPlanificadaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.Entities.AccionPlanificada", "NuevaAccionPlanificada")
                        .WithMany()
                        .HasForeignKey("NuevaAccionPlanificadaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.Entities.RevisionKaizen", "RevisionKaizen")
                        .WithMany("Ajustes")
                        .HasForeignKey("RevisionKaizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionPlanificada");

                    b.Navigation("NuevaAccionPlanificada");

                    b.Navigation("RevisionKaizen");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.EvaluacionKaizen", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Meta", "Meta")
                        .WithOne("Evaluacion")
                        .HasForeignKey("Kaizen.Domain.Entities.EvaluacionKaizen", "MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.EventoHistorialMeta", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.AccionPlanificada", "AccionPlanificada")
                        .WithMany()
                        .HasForeignKey("AccionPlanificadaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.Entities.Meta", "Meta")
                        .WithMany("EventosHistorial")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Kaizen.Domain.Entities.RevisionKaizen", "RevisionKaizen")
                        .WithMany()
                        .HasForeignKey("RevisionKaizenId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AccionPlanificada");

                    b.Navigation("Meta");

                    b.Navigation("RevisionKaizen");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Meta", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.AreaPersonal", "AreaPersonal")
                        .WithMany("Metas")
                        .HasForeignKey("AreaPersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaPersonal");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.RegistroAccion", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.AccionProgramada", "AccionProgramada")
                        .WithOne("Registro")
                        .HasForeignKey("Kaizen.Domain.Entities.RegistroAccion", "AccionProgramadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionProgramada");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.RevisionKaizen", b =>
                {
                    b.HasOne("Kaizen.Domain.Entities.Meta", "Meta")
                        .WithMany("Revisiones")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionPlanificada", b =>
                {
                    b.Navigation("AccionesProgramadas");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AccionProgramada", b =>
                {
                    b.Navigation("Registro");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.AreaPersonal", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.Meta", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Evaluacion");

                    b.Navigation("EventosHistorial");

                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("Kaizen.Domain.Entities.RevisionKaizen", b =>
                {
                    b.Navigation("Ajustes");
                });
#pragma warning restore 612, 618
        }
    }
}
