// <auto-generated />
using System;
using Kaizen.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Kaizen.Infrastructure.Migrations
{
    [DbContext(typeof(KaizenDbContext))]
    [Migration("20260803150032_DecimalPrecision")]
    partial class DecimalPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Kaizen.Domain.ActionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("ValorReal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nota")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccionProgramadaId")
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionProgramadaId")
                        .IsUnique();

                    b.ToTable("RegistrosAccion");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionPlanificada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaFin")
                        .HasColumnType("date");

                    b.Property<int>("DificultadEstimada")
                        .HasColumnType("int");

                    b.Property<int>("Frecuencia")
                        .HasColumnType("int");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("UnidadMetrica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<decimal?>("CantidadObjetivo")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<TimeOnly?>("Hora")
                        .HasColumnType("time");

                    b.Property<string>("DiasSemana")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("AccionesPlanificadas");
                });

            modelBuilder.Entity("Kaizen.Domain.Meta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SituacionActual")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ResultadoEsperado")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("FechaProximaRevision")
                        .HasColumnType("date");

                    b.Property<int>("AreaPersonalId")
                        .HasColumnType("int");

                    b.Property<string>("MetricaProgreso")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FrecuenciaRevision")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("date");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaObjetivo")
                        .HasColumnType("date");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PorQueEsImportante")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AreaPersonalId");

                    b.ToTable("Metas");
                });

            modelBuilder.Entity("Kaizen.Domain.KaizenAssessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<string>("EvidenciaMejora")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Obstaculos")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DificultadPercibida")
                        .HasColumnType("int");

                    b.Property<string>("MejoraMasPequena")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueCambiar")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueFunciona")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DondeEstoy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId")
                        .IsUnique();

                    b.ToTable("EvaluacionesKaizen");
                });

            modelBuilder.Entity("Kaizen.Domain.RevisionKaizen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("SugerenciaAutomatica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PorcentajeCumplimiento")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("MetaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FinPeriodo")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InicioPeriodo")
                        .HasColumnType("date");

                    b.Property<string>("AjustePequeno")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("FueDemasiadoDificil")
                        .HasColumnType("bit");

                    b.Property<string>("QueDificulto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueFunciono")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MetaId");

                    b.ToTable("RevisionesKaizen");
                });

            modelBuilder.Entity("Kaizen.Domain.AreaPersonal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AreasPersonales");
                });

            modelBuilder.Entity("Kaizen.Domain.PlanAdjustment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RevisionKaizenId")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionPlanificadaId");

                    b.HasIndex("RevisionKaizenId");

                    b.ToTable("AjustesPlan");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionProgramada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccionPlanificadaId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FechaProgramada")
                        .HasColumnType("date");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccionPlanificadaId", "FechaProgramada")
                        .IsUnique();

                    b.ToTable("AccionesProgramadas");
                });

            modelBuilder.Entity("Kaizen.Domain.ActionLog", b =>
                {
                    b.HasOne("Kaizen.Domain.AccionProgramada", "AccionProgramada")
                        .WithOne("Registro")
                        .HasForeignKey("Kaizen.Domain.ActionLog", "AccionProgramadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionProgramada");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionPlanificada", b =>
                {
                    b.HasOne("Kaizen.Domain.Meta", "Meta")
                        .WithMany("Acciones")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Kaizen.Domain.Meta", b =>
                {
                    b.HasOne("Kaizen.Domain.AreaPersonal", "AreaPersonal")
                        .WithMany("Metas")
                        .HasForeignKey("AreaPersonalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AreaPersonal");
                });

            modelBuilder.Entity("Kaizen.Domain.KaizenAssessment", b =>
                {
                    b.HasOne("Kaizen.Domain.Meta", "Meta")
                        .WithOne("Evaluacion")
                        .HasForeignKey("Kaizen.Domain.KaizenAssessment", "MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Kaizen.Domain.RevisionKaizen", b =>
                {
                    b.HasOne("Kaizen.Domain.Meta", "Meta")
                        .WithMany("Revisiones")
                        .HasForeignKey("MetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meta");
                });

            modelBuilder.Entity("Kaizen.Domain.PlanAdjustment", b =>
                {
                    b.HasOne("Kaizen.Domain.AccionPlanificada", "AccionPlanificada")
                        .WithMany()
                        .HasForeignKey("AccionPlanificadaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("Kaizen.Domain.RevisionKaizen", "RevisionKaizen")
                        .WithMany("Ajustes")
                        .HasForeignKey("RevisionKaizenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionPlanificada");

                    b.Navigation("RevisionKaizen");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionProgramada", b =>
                {
                    b.HasOne("Kaizen.Domain.AccionPlanificada", "AccionPlanificada")
                        .WithMany("AccionesProgramadas")
                        .HasForeignKey("AccionPlanificadaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AccionPlanificada");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionPlanificada", b =>
                {
                    b.Navigation("AccionesProgramadas");
                });

            modelBuilder.Entity("Kaizen.Domain.Meta", b =>
                {
                    b.Navigation("Acciones");

                    b.Navigation("Evaluacion");

                    b.Navigation("Revisiones");
                });

            modelBuilder.Entity("Kaizen.Domain.RevisionKaizen", b =>
                {
                    b.Navigation("Ajustes");
                });

            modelBuilder.Entity("Kaizen.Domain.AreaPersonal", b =>
                {
                    b.Navigation("Metas");
                });

            modelBuilder.Entity("Kaizen.Domain.AccionProgramada", b =>
                {
                    b.Navigation("Registro");
                });
#pragma warning restore 612, 618
        }
    }
}
