using Kaizen.Infrastructure.Persistence;
using Kaizen.Domain.Entities;
using Kaizen.Web.Services;
using Kaizen.Domain.Rules;
using Kaizen.Web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Authorization;
namespace Kaizen.Web.Controllers;

[Authorize]
public class GoalsController(ApplicationDbContext db, GoalProgressService progress, ScheduleService schedule, GoalActivationService activation, GoalHistoryService history, DeletionService deletion, ManualActionEditService manualEdit, ILogger<GoalsController> logger) : Controller
{
    public async Task<IActionResult> Index(bool archived = false) { ViewBag.ShowArchived = archived; var goals = await db.Metas.Include(x => x.AreaPersonal).Where(x => archived ? x.Estado == EstadoMeta.Archivada : x.Estado != EstadoMeta.Archivada).ToListAsync(); return View(await progress.EvaluateAsync(goals)); }
    public async Task<IActionResult> Details(int id, int historyPage = 1, CancellationToken ct = default) { var goal = await db.Metas.Include(x => x.AreaPersonal).Include(x => x.Evaluacion).Include(x => x.Acciones).Include(x => x.Revisiones).ThenInclude(x => x.Ajustes).SingleOrDefaultAsync(x => x.Id == id, ct); if (goal is null) return NotFound(); ViewBag.Progress = (await progress.EvaluateAsync([goal])).Single(); ViewBag.History = await history.GetAsync(id, historyPage, 30, ct); ViewBag.HistoryPage = historyPage; ViewBag.ReviewDue = goal.Estado == EstadoMeta.Activa && goal.FechaProximaRevision <= DateOnly.FromDateTime(DateTime.Today); return View(goal); }
    public async Task<IActionResult> Create(int? id) { await Areas(); if (id is null) return View(new GoalSetupViewModel()); var g = await db.Metas.AsNoTracking().Include(x => x.Evaluacion).Include(x => x.Acciones).SingleOrDefaultAsync(x => x.Id == id && x.Estado == EstadoMeta.Borrador); if (g is null) return NotFound(); return View(new GoalSetupViewModel { Id = g.Id, Titulo = g.Titulo, Descripcion = g.Descripcion, AreaPersonalId = g.AreaPersonalId, FechaInicio = g.FechaInicio, FechaObjetivo = g.FechaObjetivo, MetricaProgreso = g.MetricaProgreso, PorQueEsImportante = g.PorQueEsImportante, SituacionActual = g.SituacionActual, ResultadoEsperado = g.ResultadoEsperado, Obstaculos = g.Evaluacion?.Obstaculos ?? "", QueFunciona = g.Evaluacion?.QueFunciona ?? "", MejoraMasPequena = g.Evaluacion?.MejoraMasPequena ?? "", EvidenciaMejora = g.Evaluacion?.EvidenciaMejora ?? "", DificultadPercibida = g.Evaluacion?.DificultadPercibida ?? 3, Acciones = g.Acciones.Select(x => new GoalSetupActionViewModel { Nombre = x.Nombre, Frecuencia = x.Frecuencia, DiasSemana = x.DiasSemana, Hora = x.Hora, FechaInicio = x.FechaInicio, FechaFin = x.FechaFin, CantidadObjetivo = x.CantidadObjetivo, UnidadMetrica = x.UnidadMetrica, DificultadEstimada = x.DificultadEstimada }).DefaultIfEmpty(new()).ToList() }); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> Create(GoalSetupViewModel vm, CancellationToken ct) { var activate = vm.SubmitIntent == "activate"; if (vm.Id > 0 && !await db.Metas.AnyAsync(x => x.Id == vm.Id && x.Estado == EstadoMeta.Borrador, ct)) ModelState.AddModelError(string.Empty, "El borrador ya no existe o ya fue activado."); if (!ModelState.IsValid) { await Areas(); return View(vm); } try { var id = await activation.SaveAsync(vm, activate, ct); TempData["SuccessMessage"] = activate ? "La meta se guardó y activó correctamente." : "La meta se guardó como borrador."; return RedirectToAction(nameof(Index)); } catch (Exception ex) { logger.LogError(ex, "No se pudo guardar la meta {MetaId} con intención {Intent}.", vm.Id, vm.SubmitIntent); ModelState.AddModelError(string.Empty, "No se pudo guardar la meta. Intentá nuevamente."); await Areas(); return View(vm); } }
    public async Task<IActionResult> Edit(int id) { var g = await db.Metas.SingleOrDefaultAsync(x => x.Id == id); if (g is null) return NotFound(); if (g.Estado == EstadoMeta.Archivada) return RedirectToAction(nameof(Details), new { id }); await Areas(); return View(new GoalFormViewModel { Id = g.Id, Titulo = g.Titulo, Descripcion = g.Descripcion, AreaPersonalId = g.AreaPersonalId, PorQueEsImportante = g.PorQueEsImportante, SituacionActual = g.SituacionActual, ResultadoEsperado = g.ResultadoEsperado, FechaInicio = g.FechaInicio, FechaObjetivo = g.FechaObjetivo, MetricaProgreso = g.MetricaProgreso }); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> Edit(GoalFormViewModel vm) { if (!ModelState.IsValid) { await Areas(); return View(vm); } var g = await db.Metas.SingleOrDefaultAsync(x => x.Id == vm.Id); if (g is null) return NotFound(); g.Titulo = vm.Titulo; g.Descripcion = vm.Descripcion; g.AreaPersonalId = vm.AreaPersonalId; g.PorQueEsImportante = vm.PorQueEsImportante; g.SituacionActual = vm.SituacionActual; g.ResultadoEsperado = vm.ResultadoEsperado; g.FechaInicio = vm.FechaInicio; g.FechaObjetivo = vm.FechaObjetivo; g.MetricaProgreso = vm.MetricaProgreso; await db.SaveChangesAsync(); return RedirectToAction(nameof(Details), new { id = g.Id }); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> Pause(int id) { var g = await db.Metas.SingleOrDefaultAsync(x => x.Id == id); if (g is null) return NotFound(); g.Estado = EstadoMeta.Pausada; await db.SaveChangesAsync(); return RedirectToAction(nameof(Details), new { id }); }
    [HttpGet] public async Task<IActionResult> Evaluacion(int id) { var g = await db.Metas.Include(x => x.Evaluacion).SingleOrDefaultAsync(x => x.Id == id); if (g is null) return NotFound(); var a = g.Evaluacion; return View(new AssessmentFormViewModel { MetaId = g.Id, GoalTitle = g.Titulo, DondeEstoy = a?.DondeEstoy ?? "", QueCambiar = a?.QueCambiar ?? "", Obstaculos = a?.Obstaculos ?? "", QueFunciona = a?.QueFunciona ?? "", MejoraMasPequena = a?.MejoraMasPequena ?? "", EvidenciaMejora = a?.EvidenciaMejora ?? "", DificultadPercibida = a?.DificultadPercibida ?? 3 }); }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> Evaluacion(int id, AssessmentFormViewModel vm, CancellationToken ct)
    {
        if (id != vm.MetaId) ModelState.AddModelError(nameof(vm.MetaId), "La meta asociada no coincide con la solicitud.");
        var goal = await db.Metas.Include(x => x.Evaluacion).SingleOrDefaultAsync(x => x.Id == id, ct);
        if (goal is null) ModelState.AddModelError(nameof(vm.MetaId), "La meta asociada ya no existe."); else vm.GoalTitle = goal.Titulo;
        if (!ModelState.IsValid) return View(vm);
        await using var transaction = await db.Database.BeginTransactionAsync(ct);
        try
        {
            var assessment = goal!.Evaluacion ?? new EvaluacionKaizen { MetaId = goal.Id };
            assessment.DondeEstoy = vm.DondeEstoy.Trim(); assessment.QueCambiar = vm.QueCambiar.Trim(); assessment.Obstaculos = vm.Obstaculos.Trim(); assessment.QueFunciona = vm.QueFunciona.Trim(); assessment.MejoraMasPequena = vm.MejoraMasPequena.Trim(); assessment.EvidenciaMejora = vm.EvidenciaMejora.Trim(); assessment.DificultadPercibida = vm.DificultadPercibida;
            if (goal.Evaluacion is null) db.EvaluacionesKaizen.Add(assessment);
            goal.Estado = EstadoMeta.Activa; goal.FechaProximaRevision = DateOnly.FromDateTime(DateTime.Today).AddDays(7);
            await db.SaveChangesAsync(ct);
            var today = DateOnly.FromDateTime(DateTime.Today); var horizon = goal.FechaObjetivo is { } target && target < today.AddDays(ScheduleService.MaximumHorizonDays) ? target : today.AddDays(ScheduleService.MaximumHorizonDays); if (horizon >= today) await schedule.EnsureGoalScheduledAsync(goal.Id, today, horizon, ct);
            await transaction.CommitAsync(ct); TempData["SuccessMessage"] = "La meta se guardó y activó correctamente."; return RedirectToAction(nameof(Index));
        }
        catch (Exception ex)
        {
            await transaction.RollbackAsync(CancellationToken.None); logger.LogError(ex, "No se pudo guardar y activar la meta {MetaId}.", id); ModelState.AddModelError(string.Empty, "No se pudo guardar y activar la meta. Revisá los datos e intentá nuevamente."); return View(vm);
        }
    }
    public async Task<IActionResult> AddAction(int id) { if (!await db.Metas.AnyAsync(x => x.Id == id && x.Estado != EstadoMeta.Archivada)) return NotFound(); return View(new ActionFormViewModel { MetaId = id }); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> AddAction(int id, ActionFormViewModel vm, CancellationToken ct) { if (id != vm.MetaId) ModelState.AddModelError(nameof(vm.MetaId), "La meta asociada no coincide con la solicitud."); var goal = await db.Metas.SingleOrDefaultAsync(x => x.Id == vm.MetaId, ct); if (goal is null) ModelState.AddModelError(nameof(vm.MetaId), "La meta asociada ya no existe."); if (!ModelState.IsValid) return View(vm); await using var transaction = await db.Database.BeginTransactionAsync(ct); var start = vm.FechaInicio!.Value; var action = new AccionPlanificada { MetaId = vm.MetaId, Nombre = vm.Nombre.Trim(), Descripcion = vm.Descripcion?.Trim() ?? "", Frecuencia = vm.Frecuencia, DiasSemana = vm.DiasSemana, Hora = vm.Hora, FechaInicio = start, VigenteDesde = start, FechaFin = vm.FechaFin, DificultadEstimada = vm.DificultadEstimada, CantidadObjetivo = vm.CantidadObjetivo, UnidadMetrica = vm.UnidadMetrica?.Trim(), Estado = EstadoAccion.Activa }; db.AccionesPlanificadas.Add(action); db.EventosHistorialMeta.Add(new() { MetaId = vm.MetaId, AccionPlanificada = action, Tipo = TipoEventoHistorialMeta.AccionAgregada, Descripcion = $"Acción agregada: {action.Nombre}." }); await db.SaveChangesAsync(ct); var today = DateOnly.FromDateTime(DateTime.Today); var horizon = today.AddDays(ScheduleService.MaximumHorizonDays); if (action.FechaFin is { } actionEnd && actionEnd < horizon) horizon = actionEnd; if (goal!.FechaObjetivo is { } goalEnd && goalEnd < horizon) horizon = goalEnd; if (horizon >= today) await schedule.EnsureGoalScheduledAsync(goal.Id, today, horizon, ct); await transaction.CommitAsync(ct); TempData["SuccessMessage"] = "La acción se agregó correctamente."; return RedirectToAction(nameof(Details), new { id = vm.MetaId }); }
    [HttpGet] public async Task<IActionResult> EditAction(int id, CancellationToken ct) { var vm = await manualEdit.BuildAsync(id, ct); return vm is null ? NotFound() : View(vm); }
    [HttpPost, ValidateAntiForgeryToken]
    public async Task<IActionResult> EditAction(int id, ActionEditViewModel vm, CancellationToken ct)
    {
        if (id != vm.ActionId) ModelState.AddModelError(nameof(vm.ActionId), "La acción no coincide con la solicitud."); await manualEdit.PrepareAsync(vm, ct); if (!vm.CanEdit) ModelState.AddModelError(string.Empty, "Esta es una versión histórica y no puede modificarse."); var dateError = await manualEdit.ValidateEffectiveDateAsync(vm, ct); if (dateError is not null) ModelState.AddModelError(nameof(vm.FechaVigencia), dateError); if (!ModelState.IsValid) return View(vm); if (vm.Changes.Count == 0) { ModelState.AddModelError(string.Empty, "No se detectaron cambios en la acción."); return View(vm); }
        if (vm.SubmitIntent != "confirm") return View(vm);
        try { var result = await manualEdit.SaveAsync(vm, ct); if (result.Outcome == ManualEditOutcome.NoChanges) { ModelState.AddModelError(string.Empty, "No se detectaron cambios en la acción."); return View(vm); } TempData["SuccessMessage"] = result.Outcome == ManualEditOutcome.Updated ? "La acción se modificó correctamente." : "La acción se modificó correctamente. La configuración anterior se conservó en el historial."; return RedirectToAction(nameof(Details), new { id = result.MetaId }); } catch (InvalidOperationException ex) { ModelState.AddModelError(string.Empty, ex.Message); await manualEdit.PrepareAsync(vm, ct); return View(vm); } catch (Exception ex) { logger.LogError(ex, "No se pudo modificar la acción {ActionId}.", id); ModelState.AddModelError(string.Empty, "No se pudo modificar la acción. Intentá nuevamente."); await manualEdit.PrepareAsync(vm, ct); return View(vm); }
    }
    [HttpGet] public async Task<IActionResult> Delete(int id, CancellationToken ct) { var vm = await deletion.InspectGoalAsync(id, ct); return vm is null ? NotFound() : View(vm); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> DeleteConfirmed(int id, string? reason, CancellationToken ct) { try { var result = await deletion.DeleteGoalAsync(id, reason, ct); TempData[result.Outcome == DeletionOutcome.NotFound ? "ErrorMessage" : "SuccessMessage"] = result.Outcome switch { DeletionOutcome.Deleted => "La meta se eliminó correctamente.", DeletionOutcome.Archived => "La meta se archivó correctamente y su historial fue conservado.", DeletionOutcome.AlreadyArchived => "La meta ya estaba archivada.", _ => "La meta ya no existe." }; return RedirectToAction(nameof(Index), new { archived = result.Outcome is DeletionOutcome.Archived or DeletionOutcome.AlreadyArchived }); } catch { TempData["ErrorMessage"] = "No se pudo completar la operación. Intentá nuevamente."; return RedirectToAction(nameof(Delete), new { id }); } }
    [HttpGet] public async Task<IActionResult> DeleteAction(int id, CancellationToken ct) { var vm = await deletion.InspectActionAsync(id, ct); return vm is null ? NotFound() : View(vm); }
    [HttpPost, ValidateAntiForgeryToken] public async Task<IActionResult> DeleteActionConfirmed(int id, string? reason, CancellationToken ct) { try { var result = await deletion.DeleteActionAsync(id, reason, ct); TempData[result.Outcome == DeletionOutcome.NotFound ? "ErrorMessage" : "SuccessMessage"] = result.Outcome switch { DeletionOutcome.Deleted => "La acción se eliminó correctamente.", DeletionOutcome.Archived => "La acción se archivó correctamente y su historial fue conservado.", DeletionOutcome.AlreadyArchived => "La acción ya estaba archivada.", _ => "La acción ya no existe." }; return result.MetaId is int goalId ? RedirectToAction(nameof(Details), new { id = goalId }) : RedirectToAction(nameof(Index)); } catch { TempData["ErrorMessage"] = "No se pudo completar la operación. Intentá nuevamente."; return RedirectToAction(nameof(DeleteAction), new { id }); } }
    private async Task Areas() => ViewBag.AreaPersonalId = new SelectList(await db.AreasPersonales.OrderBy(x => x.Nombre).ToListAsync(), "Id", "Nombre");
}

