using Kaizen.Infrastructure.Persistence;
using Kaizen.Domain.Entities;
using Kaizen.Web.ViewModels;
using Microsoft.EntityFrameworkCore;
namespace Kaizen.Web.Services;

public enum ManualEditOutcome { Updated, VersionCreated, NoChanges }
public sealed record ManualEditResult(ManualEditOutcome Outcome, int MetaId, int ActionId);
public sealed class ManualActionEditService(ApplicationDbContext db, ScheduleService schedule, ILogger<ManualActionEditService> logger)
{
    public async Task<ActionEditViewModel?> BuildAsync(int id, CancellationToken ct = default)
    {
        var a = await db.AccionesPlanificadas.AsNoTracking().Include(x => x.Meta).SingleOrDefaultAsync(x => x.Id == id, ct); if (a is null) return null;
        var current = await db.AccionesPlanificadas.AsNoTracking().Where(x => x.SerieAccionId == a.SerieAccionId && x.VigenteHasta == null).OrderByDescending(x => x.Version).FirstOrDefaultAsync(ct); var editable = current?.Id == a.Id && a.Estado == EstadoAccion.Activa && a.Meta!.Estado != EstadoMeta.Archivada;
        var direct = editable && await IsDirectAsync(a, ct); var safe = await FirstSafeDateAsync(a, ct); var vm = new ActionEditViewModel { ActionId = a.Id, MetaId = a.MetaId, OriginalVersion = a.Version, Nombre = a.Nombre, Descripcion = a.Descripcion, Frecuencia = a.Frecuencia, DiasSemana = a.DiasSemana, Hora = a.Hora, FechaInicio = a.FechaInicio, FechaFin = a.FechaFin, DificultadEstimada = a.DificultadEstimada, CantidadObjetivo = a.CantidadObjetivo, UnidadMetrica = a.UnidadMetrica, FechaVigencia = safe, CanEdit = editable, DirectUpdate = direct }; vm.Versions = await Versions(a.SerieAccionId, ct); return vm;
    }
    public async Task PrepareAsync(ActionEditViewModel vm, CancellationToken ct = default)
    {
        var current = await db.AccionesPlanificadas.AsNoTracking().Include(x => x.Meta).SingleOrDefaultAsync(x => x.Id == vm.ActionId, ct); if (current is null) return; vm.MetaId = current.MetaId; vm.CanEdit = current.VigenteHasta == null && current.Estado == EstadoAccion.Activa && current.Meta!.Estado != EstadoMeta.Archivada; vm.DirectUpdate = vm.CanEdit && await IsDirectAsync(current, ct); vm.Changes = Changes(current, vm); vm.HasRegisteredFuture = await db.AccionesProgramadas.AnyAsync(x => x.AccionPlanificadaId == current.Id && x.FechaProgramada >= vm.FechaVigencia && x.Registro != null, ct); vm.Versions = await Versions(current.SerieAccionId, ct);
    }
    public async Task<string?> ValidateEffectiveDateAsync(ActionEditViewModel vm, CancellationToken ct = default)
    {
        var today = DateOnly.FromDateTime(DateTime.Today); if (vm.DirectUpdate) return null; if (vm.FechaVigencia < today) return InvalidDate;
        var current = await db.AccionesPlanificadas.AsNoTracking().SingleAsync(x => x.Id == vm.ActionId, ct); if (vm.FechaVigencia < current.VigenteDesde) return InvalidDate;
        if (await db.RevisionesKaizen.AnyAsync(x => x.MetaId == current.MetaId && x.FinPeriodo >= vm.FechaVigencia, ct)) return InvalidDate;
        if (await db.AccionesProgramadas.AnyAsync(x => x.AccionPlanificadaId == current.Id && x.FechaProgramada >= vm.FechaVigencia && x.FechaProgramada < today && x.Registro != null, ct)) return InvalidDate; return null;
    }
    public async Task<ManualEditResult> SaveAsync(ActionEditViewModel vm, CancellationToken ct = default)
    {
        await using var tx = await db.Database.BeginTransactionAsync(ct); try
        {
            var current = await db.AccionesPlanificadas.Include(x => x.Meta).SingleOrDefaultAsync(x => x.Id == vm.ActionId, ct) ?? throw new InvalidOperationException("La acción ya no existe."); if (current.Version != vm.OriginalVersion || current.VigenteHasta != null || current.Estado != EstadoAccion.Activa) throw new InvalidOperationException("La versión de la acción ya cambió. Volvé a cargar la página.");
            var direct = await IsDirectAsync(current, ct); var changes = Changes(current, vm); if (changes.Count == 0) return new(ManualEditOutcome.NoChanges, current.MetaId, current.Id); var old = ChangedValues(current, vm, false); var newer = ChangedValues(current, vm, true);
            if (direct) { Apply(current, vm); db.EventosHistorialMeta.Add(new() { MetaId = current.MetaId, AccionPlanificada = current, Tipo = TipoEventoHistorialMeta.AccionModificadaManualmente, Descripcion = $"Acción modificada manualmente: {current.Nombre}.", ValoresAnteriores = old, ValoresNuevos = newer, Motivo = vm.Motivo.Trim() }); await db.SaveChangesAsync(ct); await tx.CommitAsync(ct); return new(ManualEditOutcome.Updated, current.MetaId, current.Id); }
            var invalid = await ValidateEffectiveDateAsync(vm, ct); if (invalid is not null) throw new InvalidOperationException(invalid); var future = await db.AccionesProgramadas.Where(x => x.AccionPlanificadaId == current.Id && x.FechaProgramada >= vm.FechaVigencia && x.Estado == EstadoCumplimiento.Pendiente && x.Registro == null).ToListAsync(ct); db.AccionesProgramadas.RemoveRange(future); current.VigenteHasta = vm.FechaVigencia.AddDays(-1); current.Estado = EstadoAccion.Completada;
            var next = new AccionPlanificada { MetaId = current.MetaId, Nombre = vm.Nombre.Trim(), Descripcion = vm.Descripcion?.Trim() ?? "", Frecuencia = vm.Frecuencia, DiasSemana = vm.DiasSemana, Hora = vm.Hora, FechaInicio = vm.FechaInicio!.Value, FechaFin = vm.FechaFin, DificultadEstimada = vm.DificultadEstimada, CantidadObjetivo = vm.CantidadObjetivo, UnidadMetrica = vm.UnidadMetrica?.Trim(), Estado = EstadoAccion.Activa, SerieAccionId = current.SerieAccionId, Version = current.Version + 1, VigenteDesde = vm.FechaVigencia, VersionAnteriorId = current.Id, MotivoCambio = vm.Motivo.Trim() }; db.AccionesPlanificadas.Add(next); db.EventosHistorialMeta.Add(new() { MetaId = current.MetaId, AccionPlanificada = next, Tipo = TipoEventoHistorialMeta.AccionModificadaManualmente, Descripcion = $"Acción modificada manualmente: {current.Nombre}. Vigente desde {vm.FechaVigencia:dd/MM/yyyy}.", ValoresAnteriores = old, ValoresNuevos = newer, Motivo = vm.Motivo.Trim() }); await db.SaveChangesAsync(ct);
            var today = DateOnly.FromDateTime(DateTime.Today); var from = vm.FechaVigencia > today ? vm.FechaVigencia : today; var to = from.AddDays(ScheduleService.MaximumHorizonDays); if (next.FechaFin is { } end && end < to) to = end; if (current.Meta!.FechaObjetivo is { } goalEnd && goalEnd < to) to = goalEnd; if (to >= from) await schedule.EnsureGoalScheduledAsync(current.MetaId, from, to, ct); await tx.CommitAsync(ct); return new(ManualEditOutcome.VersionCreated, current.MetaId, next.Id);
        }
        catch (Exception ex) { logger.LogError(ex, "No se pudo modificar manualmente la acción {ActionId}.", vm.ActionId); await tx.RollbackAsync(CancellationToken.None); throw; }
    }
    private async Task<bool> IsDirectAsync(AccionPlanificada a, CancellationToken ct) => a.Meta!.Estado == EstadoMeta.Borrador && a.Version == 1 && a.VersionAnteriorId == null && !await db.AccionesProgramadas.AnyAsync(x => x.AccionPlanificadaId == a.Id, ct) && !await db.AjustesPlan.AnyAsync(x => x.AccionPlanificadaId == a.Id || x.NuevaAccionPlanificadaId == a.Id, ct);
    private async Task<DateOnly> FirstSafeDateAsync(AccionPlanificada a, CancellationToken ct) { var today = DateOnly.FromDateTime(DateTime.Today); var last = await db.RevisionesKaizen.Where(x => x.MetaId == a.MetaId).MaxAsync(x => (DateOnly?)x.FinPeriodo, ct); return last.HasValue && last.Value >= today ? last.Value.AddDays(1) : today; }
    private async Task<List<ActionVersionViewModel>> Versions(Guid series, CancellationToken ct) { var rows = await db.AccionesPlanificadas.AsNoTracking().Where(x => x.SerieAccionId == series).OrderByDescending(x => x.Version).ToListAsync(ct); return rows.Select(x => new ActionVersionViewModel(x.Id, x.Version, x.VigenteDesde, x.VigenteHasta, ReviewService.Describe(x), x.MotivoCambio, x.RevisionOrigenId != null ? "Revisión Kaizen" : x.Version == 1 ? "Configuración inicial" : "Modificación manual", x.Estado.ToString())).ToList(); }
    private static List<string> Changes(AccionPlanificada a, ActionEditViewModel v) { var r = new List<string>(); Add(r, "Nombre", a.Nombre, v.Nombre.Trim()); Add(r, "Descripción", a.Descripcion, v.Descripcion?.Trim() ?? ""); Add(r, "Frecuencia", a.Frecuencia.ToString(), v.Frecuencia.ToString()); Add(r, "Días", a.DiasSemana ?? "-", v.DiasSemana ?? "-"); Add(r, "Horario", a.Hora?.ToString("HH:mm") ?? "-", v.Hora?.ToString("HH:mm") ?? "-"); Add(r, "Inicio", a.FechaInicio.ToString("dd/MM/yyyy"), v.FechaInicio?.ToString("dd/MM/yyyy") ?? "-"); Add(r, "Finalización", a.FechaFin?.ToString("dd/MM/yyyy") ?? "sin fecha", v.FechaFin?.ToString("dd/MM/yyyy") ?? "sin fecha"); Add(r, "Dificultad", a.DificultadEstimada.ToString(), v.DificultadEstimada.ToString()); Add(r, "Cantidad", a.CantidadObjetivo?.ToString() ?? "-", v.CantidadObjetivo?.ToString() ?? "-"); Add(r, "Unidad", a.UnidadMetrica ?? "-", v.UnidadMetrica?.Trim() ?? "-"); return r; }
    private static void Add(List<string> r, string label, string oldValue, string newValue) { if (oldValue != newValue) r.Add($"{label}: {oldValue} → {newValue}"); }
    private static string ChangedValues(AccionPlanificada a, ActionEditViewModel v, bool useNew) => string.Join("; ", Changes(a, v).Select(x => x[..(x.IndexOf(':') + 1)] + " " + (useNew ? x[(x.IndexOf('→') + 1)..].Trim() : x[(x.IndexOf(':') + 1)..x.IndexOf('→')].Trim())));
    private static void Apply(AccionPlanificada a, ActionEditViewModel v) { a.Nombre = v.Nombre.Trim(); a.Descripcion = v.Descripcion?.Trim() ?? ""; a.Frecuencia = v.Frecuencia; a.DiasSemana = v.DiasSemana; a.Hora = v.Hora; a.FechaInicio = v.FechaInicio!.Value; a.VigenteDesde = v.FechaInicio.Value; a.FechaFin = v.FechaFin; a.DificultadEstimada = v.DificultadEstimada; a.CantidadObjetivo = v.CantidadObjetivo; a.UnidadMetrica = v.UnidadMetrica?.Trim(); a.MotivoCambio = v.Motivo.Trim(); }
    public const string InvalidDate = "No se puede aplicar esta modificación desde la fecha seleccionada porque existen registros o revisiones posteriores. Elegí una fecha efectiva válida.";
}
